from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from scripts.promote_skill import promote_skill
from scripts.resource_metadata import ResourceWorkflowError, default_resource_metadata, write_resource_metadata


def make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    for name in ["skills", "drafts", "extensions", "tools", "packages"]:
        (repo / name).mkdir(parents=True)
    (repo / "registry.yaml").write_text(
        "# Generated by scripts/build_registry.py. Do not edit manually.\n\n"
        "skills: {}\n"
        "drafts: {}\n"
        "extensions: {}\n"
        "tools: {}\n"
        "packages: {}\n",
        encoding="utf-8",
    )
    return repo


def make_draft(repo: Path, name: str = "alpha", *, skill_name: str | None = None) -> Path:
    draft = repo / "drafts" / name
    draft.mkdir(parents=True)
    actual_skill_name = skill_name or name
    (draft / "SKILL.md").write_text(
        f"---\nname: {actual_skill_name}\ndescription: test skill\n---\n\n# Test\n",
        encoding="utf-8",
    )
    metadata = default_resource_metadata(
        name=name,
        kind="skill",
        status="draft",
        path=f"drafts/{name}",
        source_type="self",
        source_origin=None,
        risk_level="medium",
        risk_reason="Draft skill for tests.",
        activation_mode="not-applicable",
        activation_notes="Draft skills are not linked into active skill scan paths.",
        maintenance_last_reviewed="2026-05-30",
    )
    write_resource_metadata(draft, metadata)
    return draft


def load_yaml(path: Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    assert isinstance(data, dict)
    return data


def test_promote_skill_moves_draft_to_active_skill(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = make_draft(repo, "alpha")

    destination = promote_skill(source=source, name="alpha", activation="manual", risk="low", repo_root=repo)

    assert destination == repo / "skills" / "alpha"
    assert not (repo / "drafts" / "alpha").exists()
    assert (destination / "SKILL.md").is_file()

    metadata = load_yaml(destination / "resource.yaml")
    assert metadata["name"] == "alpha"
    assert metadata["kind"] == "skill"
    assert metadata["status"] == "active"
    assert metadata["path"] == "skills/alpha"
    assert metadata["risk"]["level"] == "low"
    assert metadata["activation"]["mode"] == "manual"
    assert metadata["source"]["origin"] == "drafts/alpha"

    registry = load_yaml(repo / "registry.yaml")
    assert registry["skills"]["alpha"] == {
        "status": "active",
        "risk": "low",
        "path": "skills/alpha",
    }
    assert "alpha" not in registry.get("drafts", {})


def test_promote_skill_keep_draft_preserves_source(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = make_draft(repo, "alpha")

    destination = promote_skill(
        source=source,
        name="alpha",
        activation="manual",
        risk="low",
        repo_root=repo,
        keep_draft=True,
    )

    assert destination == repo / "skills" / "alpha"
    assert (repo / "drafts" / "alpha" / "SKILL.md").is_file()
    assert (destination / "SKILL.md").is_file()

    metadata = load_yaml(destination / "resource.yaml")
    assert metadata["name"] == "alpha"
    assert metadata["kind"] == "skill"
    assert metadata["status"] == "active"
    assert metadata["path"] == "skills/alpha"
    assert metadata["risk"]["level"] == "low"
    assert metadata["activation"]["mode"] == "manual"
    assert metadata["source"]["origin"] == "drafts/alpha"

    registry = load_yaml(repo / "registry.yaml")
    assert registry["skills"]["alpha"] == {
        "status": "active",
        "risk": "low",
        "path": "skills/alpha",
    }
    assert registry["drafts"]["alpha"] == {
        "status": "draft",
        "risk": "medium",
        "path": "drafts/alpha",
    }


def test_promote_skill_rejects_missing_skill_md(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = repo / "drafts" / "alpha"
    source.mkdir(parents=True)

    with pytest.raises(ResourceWorkflowError, match="SKILL.md missing"):
        promote_skill(source=source, name="alpha", activation="automatic", risk="medium", repo_root=repo)


def test_promote_skill_rejects_name_mismatch(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = make_draft(repo, "alpha", skill_name="beta")

    with pytest.raises(ResourceWorkflowError, match="does not match"):
        promote_skill(source=source, name="alpha", activation="automatic", risk="medium", repo_root=repo)


def test_promote_skill_rejects_existing_active_target(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = make_draft(repo, "alpha")
    (repo / "skills" / "alpha").mkdir(parents=True)

    with pytest.raises(ResourceWorkflowError, match="destination already exists"):
        promote_skill(source=source, name="alpha", activation="automatic", risk="medium", repo_root=repo)


def test_promote_skill_rejects_sources_outside_drafts(tmp_path: Path) -> None:
    repo = make_repo(tmp_path)
    source = repo / "other" / "alpha"
    source.mkdir(parents=True)
    (source / "SKILL.md").write_text("---\nname: alpha\ndescription: test\n---\n", encoding="utf-8")

    with pytest.raises(ResourceWorkflowError, match="drafts"):
        promote_skill(source=source, name="alpha", activation="automatic", risk="medium", repo_root=repo)
