from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator
from jsonschema.exceptions import ValidationError

REGISTRY_HEADER = "# Generated by scripts/build_registry.py. Do not edit manually.\n\n"
RESOURCE_FILENAME = "resource.yaml"
RESOURCE_SCHEMA_PATH = Path("schemas/resource.schema.yaml")
RESOURCE_ROOTS = ("skills", "drafts", "extensions", "tools", "packages")
REGISTRY_GROUPS = ("skills", "drafts", "extensions", "tools", "packages")
KIND_TO_GROUP = {
    "skill": "skills",
    "extension": "extensions",
    "tool": "tools",
    "package": "packages",
}
ALLOWED_RISKS = {"low", "medium", "high"}
ALLOWED_STATUSES = {"active", "archived", "draft"}
ALLOWED_KINDS = set(KIND_TO_GROUP)
ALLOWED_ACTIVATION_MODES = {"automatic", "explicit-only", "manual", "not-applicable"}

IGNORED_COPY_NAMES = {".git", "__pycache__", ".pytest_cache", ".ruff_cache", ".venv"}
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


class ResourceWorkflowError(RuntimeError):
    """Raised when an import or promotion workflow cannot proceed safely."""


@dataclass(frozen=True)
class ResourceIssue:
    location: str
    message: str

    def format(self) -> str:
        return f"{self.location}: {self.message}"


@dataclass(frozen=True)
class ResourceMetadata:
    file: Path
    data: dict[str, Any]

    @property
    def name(self) -> str:
        return str(self.data.get("name", ""))

    @property
    def kind(self) -> str:
        return str(self.data.get("kind", ""))

    @property
    def status(self) -> str:
        return str(self.data.get("status", ""))

    @property
    def path(self) -> str:
        return str(self.data.get("path", ""))

    @property
    def risk_level(self) -> str:
        risk = self.data.get("risk")
        if isinstance(risk, dict):
            return str(risk.get("level", ""))
        return ""


def load_resource_file(path: Path) -> ResourceMetadata:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        data = {}
    return ResourceMetadata(file=path, data=data)


def discover_resource_files(repo_root: Path) -> list[Path]:
    files: list[Path] = []
    for root_name in RESOURCE_ROOTS:
        root = repo_root / root_name
        if not root.is_dir():
            continue
        for child in sorted(root.iterdir()):
            candidate = child / RESOURCE_FILENAME
            if child.is_dir() and candidate.is_file():
                files.append(candidate)
    return files


def discover_resources(repo_root: Path) -> list[ResourceMetadata]:
    return [load_resource_file(path) for path in discover_resource_files(repo_root)]


def load_resource_schema(repo_root: Path) -> dict[str, Any]:
    schema_path = repo_root / RESOURCE_SCHEMA_PATH
    if not schema_path.is_file():
        schema_path = Path(__file__).resolve().parents[1] / RESOURCE_SCHEMA_PATH
    data = yaml.safe_load(schema_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ResourceWorkflowError(f"resource schema root must be a mapping: {schema_path}")
    return data


def schema_validator(repo_root: Path) -> Draft202012Validator:
    return Draft202012Validator(load_resource_schema(repo_root))


def validate_resource(
    resource: ResourceMetadata,
    *,
    repo_root: Path,
    validator: Draft202012Validator | None = None,
) -> list[ResourceIssue]:
    location = str(resource.file.relative_to(repo_root)) if resource.file.is_relative_to(repo_root) else str(resource.file)
    issues = schema_issues(resource.data, location=location, validator=validator or schema_validator(repo_root))
    issues.extend(validate_resource_invariants(resource, repo_root=repo_root, location=location))
    return issues


def schema_issues(data: dict[str, Any], *, location: str, validator: Draft202012Validator) -> list[ResourceIssue]:
    issues: list[ResourceIssue] = []
    for error in sorted(validator.iter_errors(data), key=validation_error_sort_key):
        path = ".".join(str(part) for part in error.absolute_path)
        issue_location = f"{location}:{path}" if path else location
        issues.append(ResourceIssue(issue_location, normalize_validation_message(error)))
    return issues


def validation_error_sort_key(error: ValidationError) -> tuple[str, str]:
    return (".".join(str(part) for part in error.absolute_path), error.message)


def normalize_validation_message(error: ValidationError) -> str:
    return error.message.replace("'null'", "null")


def validate_resource_invariants(resource: ResourceMetadata, *, repo_root: Path, location: str) -> list[ResourceIssue]:
    data = resource.data
    issues: list[ResourceIssue] = []

    if resource.name and resource.name != resource.file.parent.name:
        issues.append(ResourceIssue(location, f"name {resource.name!r} must match directory {resource.file.parent.name!r}"))

    expected_path = resource.file.parent.relative_to(repo_root).as_posix() if resource.file.is_relative_to(repo_root) else None
    if expected_path is not None and resource.path and resource.path != expected_path:
        issues.append(ResourceIssue(location, f"path {resource.path!r} must match actual path {expected_path!r}"))
    if resource.path and not (repo_root / resource.path).is_dir():
        issues.append(ResourceIssue(location, f"path does not exist or is not a directory: {resource.path}"))

    group = registry_group(resource)
    if not group:
        issues.append(ResourceIssue(location, f"kind {data.get('kind')!r} does not map to a registry group"))
    if resource.status == "draft" and not resource.path.startswith("drafts/"):
        issues.append(ResourceIssue(location, "draft resources must live under drafts/"))
    if resource.path.startswith("drafts/") and resource.status != "draft":
        issues.append(ResourceIssue(location, "resources under drafts/ must use status: draft"))

    return issues


def validate_resources(resources: list[ResourceMetadata], *, repo_root: Path) -> list[ResourceIssue]:
    issues: list[ResourceIssue] = []
    seen: set[tuple[str, str]] = set()
    validator = schema_validator(repo_root)
    for resource in resources:
        issues.extend(validate_resource(resource, repo_root=repo_root, validator=validator))
        group = registry_group(resource)
        key = (group, resource.name)
        if key in seen:
            issues.append(ResourceIssue(str(resource.file), f"duplicate resource key: {group}.{resource.name}"))
        seen.add(key)
    return issues


def registry_group(resource: ResourceMetadata) -> str:
    if resource.kind == "skill" and resource.path.startswith("drafts/"):
        return "drafts"
    return KIND_TO_GROUP.get(resource.kind, "")


def build_registry(resources: list[ResourceMetadata]) -> dict[str, dict[str, dict[str, str]]]:
    registry: dict[str, dict[str, dict[str, str]]] = {group: {} for group in REGISTRY_GROUPS}
    for resource in sorted(resources, key=lambda item: (registry_group(item), item.name)):
        group = registry_group(resource)
        if not group:
            continue
        registry[group][resource.name] = {
            "status": resource.status,
            "risk": resource.risk_level,
            "path": resource.path,
        }
    return registry


def format_registry(registry: dict[str, dict[str, dict[str, str]]]) -> str:
    ordered = {group: registry.get(group, {}) for group in REGISTRY_GROUPS}
    body = yaml.safe_dump(ordered, sort_keys=False, allow_unicode=True)
    return REGISTRY_HEADER + body


def generated_registry(repo_root: Path) -> tuple[str, list[ResourceIssue]]:
    resources = discover_resources(repo_root)
    issues = validate_resources(resources, repo_root=repo_root)
    return format_registry(build_registry(resources)), issues


def parse_skill_frontmatter(path: Path) -> dict[str, str]:
    match = FRONTMATTER_RE.search(path.read_text(encoding="utf-8"))
    if match is None:
        return {}

    values: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line or line.startswith((" ", "-")):
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip("\"'")
    return values


def copy_resource_tree(source: Path, destination: Path) -> None:
    source = source.resolve()
    if not source.is_dir():
        raise ResourceWorkflowError(f"source is not a directory: {source}")
    if destination.exists():
        raise ResourceWorkflowError(f"destination already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)

    def ignore(_directory: str, names: list[str]) -> set[str]:
        return {name for name in names if name in IGNORED_COPY_NAMES}

    shutil.copytree(source, destination, ignore=ignore)


def write_resource_metadata(resource_dir: Path, data: dict[str, Any]) -> None:
    resource_dir.mkdir(parents=True, exist_ok=True)
    (resource_dir / RESOURCE_FILENAME).write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def default_resource_metadata(
    *,
    name: str,
    kind: str,
    status: str,
    path: str,
    source_type: str,
    source_origin: str | None,
    risk_level: str,
    risk_reason: str,
    activation_mode: str,
    activation_notes: str,
    source_references: list[dict[str, str | None]] | None = None,
    source_imported: str | None = None,
    source_promoted: str | None = None,
    source_notes: list[str] | None = None,
    verification_commands: list[str] | None = None,
    verification_notes: list[str] | None = None,
    maintenance_last_reviewed: str,
    maintenance_notes: list[str] | None = None,
    related_upstream: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "kind": kind,
        "status": status,
        "path": path,
        "source": {
            "type": source_type,
            "origin": source_origin,
            "references": source_references or [],
            "imported": source_imported,
            "promoted": source_promoted,
            "notes": source_notes or [],
        },
        "risk": {
            "level": risk_level,
            "reason": risk_reason,
        },
        "activation": {
            "mode": activation_mode,
            "notes": activation_notes,
        },
        "verification": {
            "commands": verification_commands or [],
            "notes": verification_notes or [],
        },
        "maintenance": {
            "last_reviewed": maintenance_last_reviewed,
            "notes": maintenance_notes or [],
        },
        "relationships": {
            "extensions": [],
            "tools": [],
            "packages": [],
            "upstream": related_upstream or [],
        },
    }


def regenerate_registry(repo_root: Path) -> None:
    content, issues = generated_registry(repo_root)
    if issues:
        details = "\n".join(issue.format() for issue in issues)
        raise ResourceWorkflowError(f"resource metadata invalid:\n{details}")
    (repo_root / "registry.yaml").write_text(content, encoding="utf-8")
