from __future__ import annotations

import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

REGISTRY_HEADER = "# Generated by scripts/build_registry.py. Do not edit manually.\n\n"
RESOURCE_FILENAME = "resource.yaml"
RESOURCE_ROOTS = ("skills", "drafts", "extensions", "tools", "packages")
REGISTRY_GROUPS = ("skills", "drafts", "extensions", "tools", "packages")
KIND_TO_GROUP = {
    "skill": "skills",
    "extension": "extensions",
    "tool": "tools",
    "package": "packages",
}
ALLOWED_KINDS = set(KIND_TO_GROUP)
ALLOWED_RISKS = {"low", "medium", "high"}
ALLOWED_STATUSES = {"active", "archived", "draft"}
ALLOWED_ACTIVATION_MODES = {"automatic", "explicit-only", "manual", "not-applicable"}
REQUIRED_TOP_LEVEL = {
    "name",
    "kind",
    "status",
    "path",
    "source",
    "risk",
    "activation",
    "verification",
    "maintenance",
    "relationships",
}
REQUIRED_RELATIONSHIPS = {"extensions", "tools", "packages", "upstream"}


IGNORED_COPY_NAMES = {".git", "__pycache__", ".pytest_cache", ".ruff_cache", ".venv"}
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


class ResourceWorkflowError(RuntimeError):
    """Raised when an import or promotion workflow cannot proceed safely."""


@dataclass(frozen=True)
class ResourceIssue:
    location: str
    message: str

    def format(self) -> str:
        return f"{self.location}: {self.message}"


@dataclass(frozen=True)
class ResourceMetadata:
    file: Path
    data: dict[str, Any]

    @property
    def name(self) -> str:
        return str(self.data.get("name", ""))

    @property
    def kind(self) -> str:
        return str(self.data.get("kind", ""))

    @property
    def status(self) -> str:
        return str(self.data.get("status", ""))

    @property
    def path(self) -> str:
        return str(self.data.get("path", ""))

    @property
    def risk_level(self) -> str:
        risk = self.data.get("risk")
        if isinstance(risk, dict):
            return str(risk.get("level", ""))
        return ""


def load_resource_file(path: Path) -> ResourceMetadata:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        data = {}
    return ResourceMetadata(file=path, data=data)


def discover_resource_files(repo_root: Path) -> list[Path]:
    files: list[Path] = []
    for root_name in RESOURCE_ROOTS:
        root = repo_root / root_name
        if not root.is_dir():
            continue
        for child in sorted(root.iterdir()):
            candidate = child / RESOURCE_FILENAME
            if child.is_dir() and candidate.is_file():
                files.append(candidate)
    return files


def discover_resources(repo_root: Path) -> list[ResourceMetadata]:
    return [load_resource_file(path) for path in discover_resource_files(repo_root)]


def validate_resource(resource: ResourceMetadata, *, repo_root: Path) -> list[ResourceIssue]:
    data = resource.data
    location = str(resource.file.relative_to(repo_root)) if resource.file.is_relative_to(repo_root) else str(resource.file)
    issues: list[ResourceIssue] = []

    missing = REQUIRED_TOP_LEVEL - set(data)
    for field in sorted(missing):
        issues.append(ResourceIssue(location, f"missing required field: {field}"))

    name = data.get("name")
    if not isinstance(name, str) or not name:
        issues.append(ResourceIssue(location, "name must be a non-empty string"))
    elif name != resource.file.parent.name:
        issues.append(ResourceIssue(location, f"name {name!r} must match directory {resource.file.parent.name!r}"))

    kind = data.get("kind")
    if kind not in ALLOWED_KINDS:
        issues.append(ResourceIssue(location, f"invalid kind: {kind!r}"))

    status = data.get("status")
    if status not in ALLOWED_STATUSES:
        issues.append(ResourceIssue(location, f"invalid status: {status!r}"))

    path_value = data.get("path")
    expected_path = resource.file.parent.relative_to(repo_root).as_posix() if resource.file.is_relative_to(repo_root) else None
    if not isinstance(path_value, str) or not path_value:
        issues.append(ResourceIssue(location, "path must be a non-empty string"))
    else:
        if expected_path is not None and path_value != expected_path:
            issues.append(ResourceIssue(location, f"path {path_value!r} must match actual path {expected_path!r}"))
        if not (repo_root / path_value).is_dir():
            issues.append(ResourceIssue(location, f"path does not exist or is not a directory: {path_value}"))

    source = data.get("source")
    if not isinstance(source, dict):
        issues.append(ResourceIssue(location, "source must be a mapping"))
    elif not isinstance(source.get("type"), str) or not source.get("type"):
        issues.append(ResourceIssue(location, "source.type must be a non-empty string"))

    risk = data.get("risk")
    if not isinstance(risk, dict):
        issues.append(ResourceIssue(location, "risk must be a mapping"))
    else:
        if risk.get("level") not in ALLOWED_RISKS:
            issues.append(ResourceIssue(location, f"invalid risk.level: {risk.get('level')!r}"))
        if not isinstance(risk.get("reason"), str) or not risk.get("reason"):
            issues.append(ResourceIssue(location, "risk.reason must be a non-empty string"))

    activation = data.get("activation")
    if not isinstance(activation, dict):
        issues.append(ResourceIssue(location, "activation must be a mapping"))
    else:
        if activation.get("mode") not in ALLOWED_ACTIVATION_MODES:
            issues.append(ResourceIssue(location, f"invalid activation.mode: {activation.get('mode')!r}"))
        if not isinstance(activation.get("notes"), str):
            issues.append(ResourceIssue(location, "activation.notes must be a string"))

    verification = data.get("verification")
    if not isinstance(verification, dict):
        issues.append(ResourceIssue(location, "verification must be a mapping"))
    else:
        _validate_list_field(verification, "commands", location, issues)
        _validate_list_field(verification, "notes", location, issues)

    maintenance = data.get("maintenance")
    if not isinstance(maintenance, dict):
        issues.append(ResourceIssue(location, "maintenance must be a mapping"))
    else:
        if not isinstance(maintenance.get("last_reviewed"), str) or not maintenance.get("last_reviewed"):
            issues.append(ResourceIssue(location, "maintenance.last_reviewed must be a non-empty string"))
        _validate_list_field(maintenance, "notes", location, issues)

    relationships = data.get("relationships")
    if not isinstance(relationships, dict):
        issues.append(ResourceIssue(location, "relationships must be a mapping"))
    else:
        missing_relationships = REQUIRED_RELATIONSHIPS - set(relationships)
        for field in sorted(missing_relationships):
            issues.append(ResourceIssue(location, f"relationships missing field: {field}"))
        for field in REQUIRED_RELATIONSHIPS & set(relationships):
            _validate_list_field(relationships, field, location, issues)

    return issues


def _validate_list_field(mapping: dict[str, Any], field: str, location: str, issues: list[ResourceIssue]) -> None:
    value = mapping.get(field)
    if not isinstance(value, list):
        issues.append(ResourceIssue(location, f"{field} must be a list"))
        return
    for index, item in enumerate(value):
        if not isinstance(item, str):
            issues.append(ResourceIssue(location, f"{field}[{index}] must be a string"))


def validate_resources(resources: list[ResourceMetadata], *, repo_root: Path) -> list[ResourceIssue]:
    issues: list[ResourceIssue] = []
    seen: set[tuple[str, str]] = set()
    for resource in resources:
        issues.extend(validate_resource(resource, repo_root=repo_root))
        group = registry_group(resource)
        key = (group, resource.name)
        if key in seen:
            issues.append(ResourceIssue(str(resource.file), f"duplicate resource key: {group}.{resource.name}"))
        seen.add(key)
    return issues


def registry_group(resource: ResourceMetadata) -> str:
    if resource.kind == "skill" and resource.path.startswith("drafts/"):
        return "drafts"
    return KIND_TO_GROUP.get(resource.kind, "")


def build_registry(resources: list[ResourceMetadata]) -> dict[str, dict[str, dict[str, str]]]:
    registry: dict[str, dict[str, dict[str, str]]] = {group: {} for group in REGISTRY_GROUPS}
    for resource in sorted(resources, key=lambda item: (registry_group(item), item.name)):
        group = registry_group(resource)
        if not group:
            continue
        registry[group][resource.name] = {
            "status": resource.status,
            "risk": resource.risk_level,
            "path": resource.path,
        }
    return registry


def format_registry(registry: dict[str, dict[str, dict[str, str]]]) -> str:
    ordered = {group: registry.get(group, {}) for group in REGISTRY_GROUPS}
    body = yaml.safe_dump(ordered, sort_keys=False, allow_unicode=True)
    return REGISTRY_HEADER + body


def generated_registry(repo_root: Path) -> tuple[str, list[ResourceIssue]]:
    resources = discover_resources(repo_root)
    issues = validate_resources(resources, repo_root=repo_root)
    return format_registry(build_registry(resources)), issues

def parse_skill_frontmatter(path: Path) -> dict[str, str]:
    match = FRONTMATTER_RE.search(path.read_text(encoding="utf-8"))
    if match is None:
        return {}

    values: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line or line.startswith((" ", "-")):
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip("\"'")
    return values


def copy_resource_tree(source: Path, destination: Path) -> None:
    source = source.resolve()
    if not source.is_dir():
        raise ResourceWorkflowError(f"source is not a directory: {source}")
    if destination.exists():
        raise ResourceWorkflowError(f"destination already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)

    def ignore(_directory: str, names: list[str]) -> set[str]:
        return {name for name in names if name in IGNORED_COPY_NAMES}

    shutil.copytree(source, destination, ignore=ignore)


def write_resource_metadata(resource_dir: Path, data: dict[str, Any]) -> None:
    resource_dir.mkdir(parents=True, exist_ok=True)
    (resource_dir / RESOURCE_FILENAME).write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )


def default_resource_metadata(
    *,
    name: str,
    kind: str,
    status: str,
    path: str,
    source_type: str,
    source_origin: str | None,
    risk_level: str,
    risk_reason: str,
    activation_mode: str,
    activation_notes: str,
    verification_commands: list[str] | None = None,
    verification_notes: list[str] | None = None,
    maintenance_last_reviewed: str,
    maintenance_notes: list[str] | None = None,
    upstream: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "name": name,
        "kind": kind,
        "status": status,
        "path": path,
        "source": {
            "type": source_type,
            "origin": source_origin,
        },
        "risk": {
            "level": risk_level,
            "reason": risk_reason,
        },
        "activation": {
            "mode": activation_mode,
            "notes": activation_notes,
        },
        "verification": {
            "commands": verification_commands or [],
            "notes": verification_notes or [],
        },
        "maintenance": {
            "last_reviewed": maintenance_last_reviewed,
            "notes": maintenance_notes or [],
        },
        "relationships": {
            "extensions": [],
            "tools": [],
            "packages": [],
            "upstream": upstream or [],
        },
    }


def regenerate_registry(repo_root: Path) -> None:
    content, issues = generated_registry(repo_root)
    if issues:
        details = "\n".join(issue.format() for issue in issues)
        raise ResourceWorkflowError(f"resource metadata invalid:\n{details}")
    (repo_root / "registry.yaml").write_text(content, encoding="utf-8")
